In [4]:
import pandas as pd

In [5]:
jan20_df=pd.read_csv("Data/Jan20_citibike_tripdata.csv")
feb20_df=pd.read_csv("Data/Feb20_citibike_tripdata.csv")
mar20_df=pd.read_csv("Data/Mar20_citibike_tripdata.csv")
apr20_df=pd.read_csv("Data/Apr20_citibike_tripdata.csv")
may20_df=pd.read_csv("Data/May20_citibike_tripdata.csv")
jun20_df=pd.read_csv("Data/Jun20_citibike_tripdata.csv")
jul20_df=pd.read_csv("Data/Jul20_citibike_tripdata.csv")
aug20_df=pd.read_csv("Data/Aug20_citibike_tripdata.csv")
sep20_df=pd.read_csv("Data/Sep20_citibike_tripdata.csv")
oct20_df=pd.read_csv("Data/Oct20_citibike_tripdata.csv")
nov20_df=pd.read_csv("Data/Nov20_citibike_tripdata.csv")
dec20_df=pd.read_csv("Data/Dec20_citibike_tripdata.csv")

In [6]:
csv_file_list = ["Data/Jan20_citibike_tripdata.csv","Data/Feb20_citibike_tripdata.csv",
                "Data/Mar20_citibike_tripdata.csv","Data/Apr20_citibike_tripdata.csv","Data/May20_citibike_tripdata.csv",
                "Data/Jun20_citibike_tripdata.csv","Data/Jul20_citibike_tripdata.csv","Data/Aug20_citibike_tripdata.csv",
                "Data/Sep20_citibike_tripdata.csv","Data/Oct20_citibike_tripdata.csv","Data/Nov20_citibike_tripdata.csv",
                "Data/Dec20_citibike_tripdata.csv"]

list_of_dataframes = []
for filename in csv_file_list:
    list_of_dataframes.append(pd.read_csv(filename))

combined_df = pd.concat(list_of_dataframes)
combined_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,789,2020-01-01 00:00:55.3900,2020-01-01 00:14:05.1470,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,1
1,1541,2020-01-01 00:01:08.1020,2020-01-01 00:26:49.1780,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,1
2,1464,2020-01-01 00:01:42.1400,2020-01-01 00:26:07.0110,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,1
3,592,2020-01-01 00:01:45.5610,2020-01-01 00:11:38.1550,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,1
4,702,2020-01-01 00:01:45.7880,2020-01-01 00:13:28.2400,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,1

In [7]:
values= ("birth year"[1800:1950])

In [10]:
df = combined_df[combined_df != values]

In [11]:
df.head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,789,2020-01-01 00:00:55.3900,2020-01-01 00:14:05.1470,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,1
1,1541,2020-01-01 00:01:08.1020,2020-01-01 00:26:49.1780,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,1
2,1464,2020-01-01 00:01:42.1400,2020-01-01 00:26:07.0110,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,1
3,592,2020-01-01 00:01:45.5610,2020-01-01 00:11:38.1550,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,1
4,702,2020-01-01 00:01:45.7880,2020-01-01 00:13:28.2400,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19506857 entries, 0 to 1088928
Data columns (total 15 columns):
 #   Column                   Dtype
---  ------                   -----
 0   tripduration             int64
 1   starttime                object
 2   stoptime                 object
 3   start station id         int64
 4   start station name       object
 5   start station latitude   float64
 6   start station longitude  float64
 7   end station id           int64
 8   end station name         object
 9   end station latitude     float64
 10  end station longitude    float64
 11  bikeid                   int64
 12  usertype                 object
 13  birth year               int64
 14  gender                   int64
dtypes: float64(4), int64(6), object(5)
memory usage: 2.3+ GB

In [ ]:
combined_df.to_csv("Data/Combined_df.csv")